// Styled HTML wrapper for the PDF. Marked renders the packet Markdown into
// `bodyHtml`; this adds print-friendly typography and spacing.
export function packetHtml(bodyHtml: string, title: string): string {
  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>${escapeHtml(title)}</title>
<style>
  * { box-sizing: border-box; }
  html { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  body {
    font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #1a1a1a; font-size: 12px; line-height: 1.55; margin: 0;
  }
  h1 { font-size: 22px; margin: 0 0 4px; letter-spacing: -0.01em; }
  h2 {
    font-size: 13px; text-transform: uppercase; letter-spacing: 0.06em;
    color: #6b7280; margin: 22px 0 8px; padding-bottom: 4px;
    border-bottom: 1px solid #e5e7eb;
  }
  p { margin: 0 0 8px; }
  ul, ol { margin: 0 0 8px; padding-left: 20px; }
  li { margin: 3px 0; }
  li::marker { color: #9ca3af; }
  strong { color: #111827; }
  em { color: #6b7280; font-style: normal; }
  blockquote {
    margin: 0 0 8px; padding: 10px 14px; background: #f9fafb;
    border-left: 3px solid #d1d5db; border-radius: 4px; color: #374151;
  }
  code { background: #f3f4f6; padding: 1px 4px; border-radius: 3px; font-size: 11px; }
  .doc { max-width: 720px; margin: 0 auto; padding: 8px 4px; }
  .footer { margin-top: 28px; padding-top: 8px; border-top: 1px solid #e5e7eb;
            color: #9ca3af; font-size: 10px; }
</style>
</head>
<body>
  <div class="doc">
    ${bodyHtml}
    <div class="footer">Generated by ActionPacket AI</div>
  </div>
</body>
</html>`;
}

function escapeHtml(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c] as string,
  );
}
